# Generated by Django 2.2 on 2022-03-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text_comment',
            field=models.CharField(choices=[('d', 'Удалено администратором')], max_length=1500, verbose_name='Ваш комментарий'),
        ),
        migrations.AlterField(
            model_name='news',
            name='active_flag',
            field=models.BooleanField(choices=[(True, 'Активно'), (False, 'Неактивно')], default=False, verbose_name='Активность'),
        ),
    ]
