# Generated by Django 2.2 on 2022-03-09 01:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1500, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(max_length=1500, verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1500, verbose_name='Тип объявления')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500, verbose_name='Имя')),
                ('email', models.CharField(max_length=1500, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1500, verbose_name='заголовок')),
                ('description', models.TextField(default='описание', max_length=1500, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('public_date', models.DateTimeField(default=datetime.datetime(2022, 3, 9, 1, 33, 45, 622020), verbose_name='Дата публикации')),
                ('over_date', models.DateTimeField(default=datetime.datetime(2022, 3, 9, 1, 33, 45, 622085), verbose_name='Дата окончания публикации')),
                ('price', models.FloatField(default=0, verbose_name='цена')),
                ('views_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisments', to='advertisements_app.AuthorContact', verbose_name='Автор')),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisments', to='advertisements_app.AdvertisementHeading')),
                ('region', models.ManyToManyField(related_name='advregion', to='advertisements_app.AdvertisementRegion')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements_app.AdvertisementStatus', verbose_name='статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisments', to='advertisements_app.AdvertisementType')),
            ],
            options={
                'db_table': 'advertisement',
                'ordering': ['title'],
            },
        ),
    ]
