# Generated by Django 4.0.3 on 2022-03-22 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_news', '0002_comments_user_alter_comments_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=35, verbose_name='Город')),
                ('verification_flag', models.BooleanField(choices=[(True, 'Верифицирован'), (False, 'Неверифицирован')], default=False, verbose_name='Верификация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='app_news.tag', verbose_name='Тэги'),
        ),
    ]
