# Generated by Django 4.0.3 on 2022-03-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_tag_profile_news_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['public_date'], 'permissions': (('can_publish', 'Может публиковать'),)},
        ),
        migrations.AddField(
            model_name='profile',
            name='news_count',
            field=models.IntegerField(default=0, verbose_name='Количество опубликованный новостей'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название'),
        ),
    ]
