# Generated by Django 2.2 on 2022-03-09 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='over_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 1, 26, 57, 862866), verbose_name='Дата окончания публикации'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='public_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 1, 26, 57, 862836), verbose_name='Дата публикации'),
        ),
    ]
