# Generated by Django 2.2 on 2022-03-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20220304_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.FloatField(default=0, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(default='описание', max_length=1500, verbose_name='описание'),
        ),
    ]
