# Generated by Django 2.2 on 2022-03-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_auto_20220306_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
    ]
