# Generated by Django 2.2 on 2022-03-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0009_auto_20220306_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='region',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='type',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements.AdvertisementStatus', verbose_name='статус'),
        ),
        migrations.DeleteModel(
            name='AdvertisementRegion',
        ),
        migrations.DeleteModel(
            name='AdvertisementType',
        ),
    ]
