# Generated by Django 2.2 on 2022-03-07 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_auto_20220307_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='over_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 22, 5, 28, 695089), verbose_name='Дата окончания публикации'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='public_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 22, 5, 28, 695035), verbose_name='Дата публикации'),
        ),
    ]
