# Generated by Django 2.2 on 2022-03-07 22:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0012_auto_20220307_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=1500, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(max_length=1500, verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1500, verbose_name='Тип объявления')),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advauthor', to='advertisements.AuthorContact', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='over_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 22, 59, 32, 857015), verbose_name='Дата окончания публикации'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='public_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 22, 59, 32, 856985), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='authorcontact',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='heading',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advheading', to='advertisements.AdvertisementHeading'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='region',
            field=models.ManyToManyField(related_name='advregion', to='advertisements.AdvertisementRegion'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advtype', to='advertisements.AdvertisementType'),
        ),
    ]
