# Generated by Django 4.0.3 on 2022-03-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_alter_news_options_profile_news_count_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_give_add_news', 'Может давать права на добавление новостей'),)},
        ),
    ]
