# Generated by Django 2.2 on 2022-03-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
