# Generated by Django 2.2 on 2022-03-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_auto_20220310_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
