# Generated by Django 2.2 on 2022-03-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_auto_20220311_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='what',
            new_name='text_comment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='news',
        ),
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ManyToManyField(to='app_news.News', verbose_name='Новость'),
        ),
    ]
